# See: https://dart-lang.github.io/linter/lints/
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - 'example'
    - '**.g.dart'
    - 'test_resources/**'
  errors:
    unnecessary_import: error
    unawaited_futures: error

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_use_package_imports: true
    avoid_classes_with_only_static_members: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_renaming_method_parameters: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    flutter_style_todos: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: false
    prefer_int_literals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    use_to_and_as_if_applicable: true
    use_raw_strings: true
    use_super_parameters: false
